apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  path: ./clusters/my-cluster/crds/
  prune: true
  interval: 5m
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux2

