apiVersion: apps/v1
kind: Deployment
metadata:
  name: react2
  namespace: default
  labels:
    app: react2
spec:
  replicas: 6
  selector:
    matchLabels:
      app: react2
  template:
    metadata:
      labels:
        app: react2
    spec:
      containers:
        - name: react2
          image: skoopy365/react2:20250623-105355 # {"$imagepolicy": "flux-system:react2-app-policy"}
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /
              port: 3001 
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3001 
            initialDelaySeconds: 15
            periodSeconds: 20
