apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: react2-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react2
  interval: 10s
  filterTags:
    pattern: '^2025\.\d+\.\d+.*$'
    extract: '$0'
  policy:
    semver:
      range: '>=2025.0.0' 
