apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: react2-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react2
  policy:
    # GEÄNDERT: von 'semver' auf 'numerical' umgestellt.
    # Dies ist die korrekte Policy für numerische/datumsbasierte Tags.
    numerical:
      # 'asc' (ascending) wählt den höchsten numerischen Wert aus.
      order: asc
