apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: react2-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react2
  policy:
    semver:
      range: '>=2025.0.0' 
