---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-react2 
  namespace: default 
spec:
  secretName: cert-react2
  issuerRef:
    name: acme-issuer 
    kind: ClusterIssuer
  commonName: "react2.run.place"
  dnsNames:
  - "react2.run.place"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: react2-route
  namespace: default
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`react2.run.place`)
      kind: Rule
      services:
        - kind: Service
          name: react2
          port: 80
          namespace: default
  tls:
    secretName: cert-react2
