---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
     email: falksolution@gmail.com 
    # Letsencrypt Production
     server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
     privateKeySecretRef:
       name: issuer-account-key
     solvers:
    # DNS Challenge:
    # - dns01:
        # Configure your DNS Provider here...
        # ---
    #     cloudflare:
    #       email: falksolution@gmail.com 
       #  API Key :
    #       apiKeySecretRef:
    #         name: cloudflare-api-key-secret
    #         key: api-key 
        # - or -
        # API Token:
        #   apiTokenSecretRef:
        #     name: cloudflare-api-token-secret
        #     key: api-token        
      # (Optional) Add DNS selectors
      # ---
      # selector:
      #   dnsZones:
      #   - 'your-domain'

#       HTTP Challenge:
       - http01:
           ingress:
             class: haproxy

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-react2 
  namespace: default 
spec:
  secretName: cert-react2
  issuerRef:
    name: acme-issuer 
    kind: ClusterIssuer
  commonName: "react2.run.place"
  dnsNames:
  - "react2.run.place"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react2
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "acme-issuer"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - react2.run.place
      secretName: cert-react2
  rules:
    - host: react2.run.place
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react2
                port:
                  number: 80
