---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-falksolu 
  namespace: my-react-app
spec:
  secretName: cert-falksolu
  issuerRef:
    name: acme-issuer 
    kind: ClusterIssuer
  commonName: "lukflk.run.place"
  dnsNames:
  - "lukflk.run.place"
