apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  # This Kustomization will apply everything in the current directory and its subdirectories.
  path: ./clusters/my-cluster/apps 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
