apiVersion: image.toolkit.fluxcd.io/v1beta2 
kind: ImagePolicy
metadata:
  name: react-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: my-react-app
  policy:
    alphabetical:
      order: asc  # Uses ascending sort → picks the highest/latest
